<div class="line">
<div id="crums">
  <?php  
$cur_url = $_SERVER['REQUEST_URI'];
$img='&nbsp<img src="../img/galRigth.png">&nbsp';

$arr=array
(
$index='<a href="../index.php">Главная</a>',
$teoria='<a href="../page/teoria.php">Теория</a>',
$glava_1='<a href="../page/glava1.php">Глава I: Основа WPF</a>',
$teoria_1_1='<a href="../page/teoria_1_1.php">Появление WPF</a>',
$teoria_1_2='<a href="../page/teoria_1_2.php">Cведения о языке XAML</a>',
$teoria_1_3='<a href="../page/teoria_1_3.php">Структура WPF</a>',
$teoria_1_4='<a href="../page/teoria_1_4.php">Файлы отдельного кода</a>',
$teoria_1_5='<a href="../page/teoria_1_5.php">WPF Элементы дерева</a>',

$glava_2='<a href="../page/glava1.php">Глава II: Компановка и элементы управления WPF</a>',
$teoria_2_1='<a href="../page/teoria_2_1.php">Компановка</a>',
$teoria_2_2='<a href="../page/teoria_2_2.php">Элементы управления</a>',
$teoria_2_3='<a href="../page/teoria_2_3.php">Пользовательские элементы управления WPF</a>',
$teoria_2_4='<a href="../page/teoria_2_4.php">Элементы управления содержимым</a>',
$teoria_2_5='<a href="../page/teoria_2_5.php">Кисти фона и переднего плана</a>',
$teoria_2_6='<a href="../page/teoria_2_6.php">Использование шрифтов</a>',
$teoria_2_7='<a href="../page/teoria_2_7.php">Подстановка и встраивание шрифтов</a>',
$teoria_2_8='<a href="../page/teoria_2_8.php">Курсоры мыши</a>',
$teoria_2_9='<a href="../page/teoria_2_9.php">Выравнивание</a>',
$teoria_2_10='<a href="../page/teoria_2_10.php">Метки</a>',

$glava_3='<a href="../page/glava1.php">Глава III: Привязка, стили и команды WPF</a>',
$teoria_3_1='<a href="../page/teoria_3_1.php">Привязка элементов</a>',
$teoria_3_2='<a href="../page/teoria_3_2.php">Стили</a>',
$teoria_3_3='<a href="../page/teoria_3_3.php">Команды</a>',

$glava_4='<a href="../page/glava1.php">Глава IV: Шаблоны</a>',
$teoria_4_1='<a href="../page/teoria_3_1.php">Шаблоны</a>'
);
if($cur_url=="/page/teoria_1_1.php")
{
 echo $arr[0].$img.$arr[1].$img.$arr[2].$img.$arr[3];
}
if($cur_url=="/page/teoria_1_2.php")
{
 echo $arr[0].$img.$arr[1].$img.$arr[2].$img.$arr[4];
}
if($cur_url=="/page/teoria_1_3.php")
{
 echo $arr[0].$img.$arr[1].$img.$arr[2].$img.$arr[5];
}
if($cur_url=="/page/teoria_1_4.php")
{
 echo $arr[0].$img.$arr[1].$img.$arr[2].$img.$arr[6];
}
if($cur_url=="/page/teoria_1_5.php")
{
 echo $arr[0].$img.$arr[1].$img.$arr[2].$img.$arr[7];
}


if($cur_url=="/page/teoria_2_1.php")
{
 echo $arr[0].$img.$arr[1].$img.$arr[8].$img.$arr[9];
}
if($cur_url=="/page/teoria_2_2.php")
{
 echo $arr[0].$img.$arr[1].$img.$arr[8].$img.$arr[10];
}
if($cur_url=="/page/teoria_2_3.php")
{
 echo $arr[0].$img.$arr[1].$img.$arr[8].$img.$arr[12];
}
if($cur_url=="/page/teoria_2_4.php")
{
 echo $arr[0].$img.$arr[1].$img.$arr[8].$img.$arr[13];
}
if($cur_url=="/page/teoria_2_5.php")
{
 echo $arr[0].$img.$arr[1].$img.$arr[8].$img.$arr[14];
}
if($cur_url=="/page/teoria_2_6.php")
{
 echo $arr[0].$img.$arr[1].$img.$arr[8].$img.$arr[15];
}
if($cur_url=="/page/teoria_2_7.php")
{
 echo $arr[0].$img.$arr[1].$img.$arr[8].$img.$arr[16];
}
if($cur_url=="/page/teoria_2_8.php")
{
 echo $arr[0].$img.$arr[1].$img.$arr[8].$img.$arr[11];
}
if($cur_url=="/page/teoria_2_9.php")
{
 echo $arr[0].$img.$arr[1].$img.$arr[8].$img.$arr[17];
}
if($cur_url=="/page/teoria_2_10.php")
{
 echo $arr[0].$img.$arr[1].$img.$arr[8].$img.$arr[18];
}
if($cur_url=="/page/teoria_3_1.php")
{
 echo $arr[0].$img.$arr[1].$img.$arr[19].$img.$arr[20];
}
if($cur_url=="/page/teoria_3_2.php")
{
 echo $arr[0].$img.$arr[1].$img.$arr[19].$img.$arr[21];
}
if($cur_url=="/page/teoria_3_3.php")
{
 echo $arr[0].$img.$arr[1].$img.$arr[19].$img.$arr[22];
}
if($cur_url=="/page/teoria_4_1.php")
{
 echo $arr[0].$img.$arr[1].$img.$arr[23].$img.$arr[24];
}
if($cur_url=="/page/teoria.php")
{
 echo $arr[0].$img.$arr[1];
}
if($cur_url=="/page/glava1.php")
{
 echo $arr[0].$img.$arr[1].$img.$arr[2];
}
?>
</div>
</div>



