				<script type="text/javascript" src="../js/jquery.min.js"></script>
				<script type="text/javascript" src="../js/left_meny.js"></script>		
			<!--выпадающее меню теории-->		
				<ul id="menu">
 <li><a	 href="../index.php">Главная</a> </li>
 
 
 <li><span>Теория  &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<img src="../img/gal.png"></span>
    <ul>
        <li><span style="background:#01152D;">Глава I: Основа WPF</span>
			<ul>
				<a href="../page/teoria_1_1.php">Появление WPF</a>
				<a href="../page/teoria_1_2.php">Сведения о языке XAML</a>
				<a href="../page/teoria_1_3.php">Структура WPF</a>
				<a href="../page/teoria_1_4.php">Файлы отделенного кода</a>
				<a href="../page/teoria_1_5.php">WPF Элементы дерева</a>
			</ul>
			
		</li>
		<li><span style="background:#01152D;">Глава II: Компановка и элементы управления WPF</span>
			<ul>
				<a href="../page/teoria_2_1.php">Компановка</a>
				<a href="../page/teoria_2_2.php">Элементы управления</a>
				<a href="../page/teoria_2_8.php">Пользовательские элементы управления WPF</a>
				<a href="../page/teoria_2_3.php">Элементы управления содержимым</a>
				<a href="../page/teoria_2_4.php">Кисти фона и переднего плана</a>
				<a href="../page/teoria_2_5.php">Использование шрифтов</a>
				<a href="../page/teoria_2_6.php">Подстановка и встраивание шрифтов</a>
				<a href="../page/teoria_2_7.php">Курсоры мыши</a>
				<a href="../page/teoria_2_9.php">Выравнивание</a>
				<a href="../page/teoria_2_10.php">Метки</a>
				
			</ul>
			
		</li>
		<li><span style="background:#01152D;">Глава III: Привязка, стили и команды WPF</span>
			<ul>
				<a href="../page/teoria_3_1.php">Привязка элементов</a>
				<a href="../page/teoria_3_2.php">Стили</a>
				<a href="../page/teoria_3_3.php">Команды</a>
			</ul>			
		</li>
		   
		<li><span style="background:#01152D;">Глава IV: Шаблоны</span>
			<ul>
				<a href="../page/teoria_4_1.php">Шаблоны</a>
				
			</ul>					
		</li> 
		<li><span style="background:#01152D;">Глава V: Графика и анимация WPF</span>
			<ul>	
				<a href="csscompressor.php">Тема45615</a>
			</ul>					
		</li>
		
    </ul>
 </li>
 <li><span>Лабараторные работы &nbsp&nbsp&nbsp&nbsp<img src="../img/gal.png"></span>
    <ul>
        <li><a href="../page/laba1.php">Лабараторная работа 1</a></li>
        <li><a href="../page/laba2.php">Лабараторная работа 2</a></li>
		<li><a href="../page/laba3.php">Лабараторная работа 3</a></li>
		<li><a href="../page/laba4.php">Лабараторная работа 4</a></li>
        <li><a href="no_www.php">Выравнивание и поля</a></li>
		<li><a href="no_www.php">Минимальные и максимальные размеры</a></li>
		<li><a href="no_www.php">WrapPanel</a></li>
		<li><a href="no_www.php">DockPanel</a></li>
		<li><a href="no_www.php">Grid</a></li>
		<li><a href="no_www.php">Настройка Grid</a></li>
		<li><a href="no_www.php">GridSplitter - разделенные окна</a></li>
		<li><a href="no_www.php">Группы с общими размерами</a></li> 
		<li><a href="no_www.php">Canvas</a></li>
		<li><a href="no_www.php">InkCanvas</a></li>
		<li><a href="no_www.php">Построение приложения WPF с использованием Visual Studio 2010</a></li>
		<li><a href="no_www.php">Проектирование графического интерфейсного окна</a></li>
		<li><a href="no_www.php">StackPanel</a></li>
    </ul>
 </li>
  <li><a href="../index.php">Тесты</a> </li>
   <li><a href="../index.php">Глоссарий</a> </li>
</ul>
								
